
#define TAPPING_TERM 200
#define TAP_CODE_DELAY 50

// #define DEBUG_ACTION

#define RGB_DISABLE_WHEN_USB_SUSPENDED true
#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_JELLYBEAN_RAINDROPS
#define RGB_MATRIX_STARTUP_SPD 143
#define RGB_MATRIX_STARTUP_HUE 240
#define RGB_MATRIX_STARTUP_SAT 191
#define RGB_MATRIX_STARTUP_VAL 230
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES
